spring:
  application:
    name: market-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:market_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8082

custom:
  global:
    productServiceUrl: ${PRODUCT_SERVICE_URL:http://localhost:8081}
    paymentServiceUrl: ${PAYMENT_SERVICE_URL:http://localhost:8083}
  market:
    product:
      payoutRate: 80

jwt:
  secret: ${JWT_SECRET_KEY:}
  access-token-exp-seconds: 1800
  refresh-token-exp-seconds: 1209600
  issuer: "thock"
