spring:
  application:
    name: market-service
  profiles:
    active: local
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  datasource:
    url: jdbc:h2:./db_market;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8082

custom:
  global:
    internalBackUrl: http://localhost:8080
  market:
    product:
      payoutRate: 80

jwt:
  secret: ${JWT_SECRET_KEY:thock-2026-backend-authentication-jwt-secret-key-very-very-long-256bit}
  access-token-exp-seconds: 1800
  refresh-token-exp-seconds: 1209600
  issuer: "thock"