spring:
  datasource:
    url: jdbc:h2:file:/data/h2/db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # H2 Console (필수! 개발할 때 DB 확인용)
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true

