server:
  port: 8080
spring:
  application:
    name:Thock Backend API Server

  profiles:
    active: local

  # JPA 설정 (필수!)
  jpa:
    hibernate:
      ddl-auto: update  # 엔티티 변경 시 자동으로 테이블 생성/수정
    show-sql: true  # SQL 로그 출력

jwt:
  secret: "thock-2026-backend-authentication-jwt-secret-key-very-very-long-256bit"
  access-token-exp-seconds: 1800 # 30분
  refresh-token-exp-seconds: 1209600 # 14일
  issuer: "thock"
  
logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.orm.jdbc.bind: trace
    reactor.netty: TRACE
    org.springframework.web: TRACE

custom:
  global:
    internalBackUrl: http://localhost:${server.port:8080}
  market:
    product:
      payoutRate: 80
  payment:
    toss:
      payments:
        secretKey: ${TOSS_PAYMENTS_SECRET_KEY:}