server:
  port: 8080
spring:
  application:
    name:Thock Backend API Server

  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    username: sa
    password:
    driver-class-name: org.h2.Driver

  # H2 Console (필수! 개발할 때 DB 확인용)
  h2:
    console:
      enabled: true
      path: /h2-console

  # JPA 설정 (필수!)
  jpa:
    hibernate:
      ddl-auto: update  # 엔티티 변경 시 자동으로 테이블 생성/수정
    show-sql: true  # SQL 로그 출력

custom:
  global:
    internalBackUrl: http://localhost:${server.port:8080}