spring:
  application:
    name: payment-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:payment_db}?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8083

custom:
  global:
    internalBackUrl: http://localhost:8080
  payment:
    toss:
      payments:
        secretKey: ${TOSS_SECRET_KEY:}

jwt:
  secret: ${JWT_SECRET_KEY:}
  access-token-exp-seconds: 1800
  refresh-token-exp-seconds: 1209600
  issuer: "thock"
